// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: guessers.proto

package guessers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddGuesserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BeginAt     int64 `protobuf:"varint,1,opt,name=beginAt,proto3" json:"beginAt,omitempty"`
	IncrementBy int64 `protobuf:"varint,2,opt,name=incrementBy,proto3" json:"incrementBy,omitempty"`
	Sleep       int64 `protobuf:"varint,3,opt,name=sleep,proto3" json:"sleep,omitempty"`
}

func (x *AddGuesserRequest) Reset() {
	*x = AddGuesserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guessers_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGuesserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGuesserRequest) ProtoMessage() {}

func (x *AddGuesserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guessers_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGuesserRequest.ProtoReflect.Descriptor instead.
func (*AddGuesserRequest) Descriptor() ([]byte, []int) {
	return file_guessers_proto_rawDescGZIP(), []int{0}
}

func (x *AddGuesserRequest) GetBeginAt() int64 {
	if x != nil {
		return x.BeginAt
	}
	return 0
}

func (x *AddGuesserRequest) GetIncrementBy() int64 {
	if x != nil {
		return x.IncrementBy
	}
	return 0
}

func (x *AddGuesserRequest) GetSleep() int64 {
	if x != nil {
		return x.Sleep
	}
	return 0
}

type AddGuesserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuesserID int64 `protobuf:"varint,1,opt,name=guesserID,proto3" json:"guesserID,omitempty"`
}

func (x *AddGuesserResponse) Reset() {
	*x = AddGuesserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guessers_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGuesserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGuesserResponse) ProtoMessage() {}

func (x *AddGuesserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guessers_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGuesserResponse.ProtoReflect.Descriptor instead.
func (*AddGuesserResponse) Descriptor() ([]byte, []int) {
	return file_guessers_proto_rawDescGZIP(), []int{1}
}

func (x *AddGuesserResponse) GetGuesserID() int64 {
	if x != nil {
		return x.GuesserID
	}
	return 0
}

type RemoveGuesserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuesserID int64 `protobuf:"varint,1,opt,name=guesserID,proto3" json:"guesserID,omitempty"`
}

func (x *RemoveGuesserRequest) Reset() {
	*x = RemoveGuesserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guessers_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveGuesserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveGuesserRequest) ProtoMessage() {}

func (x *RemoveGuesserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guessers_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveGuesserRequest.ProtoReflect.Descriptor instead.
func (*RemoveGuesserRequest) Descriptor() ([]byte, []int) {
	return file_guessers_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveGuesserRequest) GetGuesserID() int64 {
	if x != nil {
		return x.GuesserID
	}
	return 0
}

type RemoveGuesserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok        bool  `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	GuesserID int64 `protobuf:"varint,2,opt,name=guesserID,proto3" json:"guesserID,omitempty"`
}

func (x *RemoveGuesserResponse) Reset() {
	*x = RemoveGuesserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guessers_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveGuesserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveGuesserResponse) ProtoMessage() {}

func (x *RemoveGuesserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guessers_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveGuesserResponse.ProtoReflect.Descriptor instead.
func (*RemoveGuesserResponse) Descriptor() ([]byte, []int) {
	return file_guessers_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveGuesserResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RemoveGuesserResponse) GetGuesserID() int64 {
	if x != nil {
		return x.GuesserID
	}
	return 0
}

type Guess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num  int64 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Time int64 `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *Guess) Reset() {
	*x = Guess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guessers_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Guess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Guess) ProtoMessage() {}

func (x *Guess) ProtoReflect() protoreflect.Message {
	mi := &file_guessers_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Guess.ProtoReflect.Descriptor instead.
func (*Guess) Descriptor() ([]byte, []int) {
	return file_guessers_proto_rawDescGZIP(), []int{4}
}

func (x *Guess) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *Guess) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type QueryGuesserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuesserID int64 `protobuf:"varint,1,opt,name=guesserID,proto3" json:"guesserID,omitempty"`
}

func (x *QueryGuesserRequest) Reset() {
	*x = QueryGuesserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guessers_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryGuesserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGuesserRequest) ProtoMessage() {}

func (x *QueryGuesserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guessers_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGuesserRequest.ProtoReflect.Descriptor instead.
func (*QueryGuesserRequest) Descriptor() ([]byte, []int) {
	return file_guessers_proto_rawDescGZIP(), []int{5}
}

func (x *QueryGuesserRequest) GetGuesserID() int64 {
	if x != nil {
		return x.GuesserID
	}
	return 0
}

type QueryGuesserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuesserID int64    `protobuf:"varint,1,opt,name=guesserID,proto3" json:"guesserID,omitempty"`
	GuessList []*Guess `protobuf:"bytes,2,rep,name=guessList,proto3" json:"guessList,omitempty"`
	Active    bool     `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
}

func (x *QueryGuesserResponse) Reset() {
	*x = QueryGuesserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guessers_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryGuesserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryGuesserResponse) ProtoMessage() {}

func (x *QueryGuesserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guessers_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryGuesserResponse.ProtoReflect.Descriptor instead.
func (*QueryGuesserResponse) Descriptor() ([]byte, []int) {
	return file_guessers_proto_rawDescGZIP(), []int{6}
}

func (x *QueryGuesserResponse) GetGuesserID() int64 {
	if x != nil {
		return x.GuesserID
	}
	return 0
}

func (x *QueryGuesserResponse) GetGuessList() []*Guess {
	if x != nil {
		return x.GuessList
	}
	return nil
}

func (x *QueryGuesserResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

type QueryPrimesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prime int64 `protobuf:"varint,1,opt,name=prime,proto3" json:"prime,omitempty"`
}

func (x *QueryPrimesRequest) Reset() {
	*x = QueryPrimesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guessers_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryPrimesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPrimesRequest) ProtoMessage() {}

func (x *QueryPrimesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guessers_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPrimesRequest.ProtoReflect.Descriptor instead.
func (*QueryPrimesRequest) Descriptor() ([]byte, []int) {
	return file_guessers_proto_rawDescGZIP(), []int{7}
}

func (x *QueryPrimesRequest) GetPrime() int64 {
	if x != nil {
		return x.Prime
	}
	return 0
}

type Primedets struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GuesserID int64 `protobuf:"varint,2,opt,name=guesserID,proto3" json:"guesserID,omitempty"`
	Time      int64 `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	OriginNum int64 `protobuf:"varint,4,opt,name=originNum,proto3" json:"originNum,omitempty"`
}

func (x *Primedets) Reset() {
	*x = Primedets{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guessers_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Primedets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Primedets) ProtoMessage() {}

func (x *Primedets) ProtoReflect() protoreflect.Message {
	mi := &file_guessers_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Primedets.ProtoReflect.Descriptor instead.
func (*Primedets) Descriptor() ([]byte, []int) {
	return file_guessers_proto_rawDescGZIP(), []int{8}
}

func (x *Primedets) GetGuesserID() int64 {
	if x != nil {
		return x.GuesserID
	}
	return 0
}

func (x *Primedets) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Primedets) GetOriginNum() int64 {
	if x != nil {
		return x.OriginNum
	}
	return 0
}

type Prime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prime     int64        `protobuf:"varint,1,opt,name=prime,proto3" json:"prime,omitempty"`
	PrimeList []*Primedets `protobuf:"bytes,2,rep,name=primeList,proto3" json:"primeList,omitempty"`
}

func (x *Prime) Reset() {
	*x = Prime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guessers_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Prime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prime) ProtoMessage() {}

func (x *Prime) ProtoReflect() protoreflect.Message {
	mi := &file_guessers_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prime.ProtoReflect.Descriptor instead.
func (*Prime) Descriptor() ([]byte, []int) {
	return file_guessers_proto_rawDescGZIP(), []int{9}
}

func (x *Prime) GetPrime() int64 {
	if x != nil {
		return x.Prime
	}
	return 0
}

func (x *Prime) GetPrimeList() []*Primedets {
	if x != nil {
		return x.PrimeList
	}
	return nil
}

type QueryPrimesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok     bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Primes []*Prime `protobuf:"bytes,2,rep,name=primes,proto3" json:"primes,omitempty"`
}

func (x *QueryPrimesResponse) Reset() {
	*x = QueryPrimesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_guessers_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryPrimesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPrimesResponse) ProtoMessage() {}

func (x *QueryPrimesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guessers_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPrimesResponse.ProtoReflect.Descriptor instead.
func (*QueryPrimesResponse) Descriptor() ([]byte, []int) {
	return file_guessers_proto_rawDescGZIP(), []int{10}
}

func (x *QueryPrimesResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *QueryPrimesResponse) GetPrimes() []*Prime {
	if x != nil {
		return x.Primes
	}
	return nil
}

var File_guessers_proto protoreflect.FileDescriptor

var file_guessers_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x67, 0x75, 0x65, 0x73, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0a, 0x67, 0x75, 0x65, 0x73, 0x73, 0x65, 0x72, 0x73, 0x70, 0x62, 0x22, 0x65, 0x0a, 0x11,
	0x61, 0x64, 0x64, 0x47, 0x75, 0x65, 0x73, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x41, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x41, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x69,
	0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x6c, 0x65, 0x65, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x6c,
	0x65, 0x65, 0x70, 0x22, 0x32, 0x0a, 0x12, 0x61, 0x64, 0x64, 0x47, 0x75, 0x65, 0x73, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x75, 0x65,
	0x73, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x67, 0x75,
	0x65, 0x73, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x34, 0x0a, 0x14, 0x72, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x47, 0x75, 0x65, 0x73, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x67, 0x75, 0x65, 0x73, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x67, 0x75, 0x65, 0x73, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x45, 0x0a,
	0x15, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x47, 0x75, 0x65, 0x73, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x75, 0x65, 0x73, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x67, 0x75, 0x65, 0x73, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x22, 0x2d, 0x0a, 0x05, 0x67, 0x75, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x22, 0x33, 0x0a, 0x13, 0x71, 0x75, 0x65, 0x72, 0x79, 0x47, 0x75, 0x65, 0x73,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x75,
	0x65, 0x73, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x67,
	0x75, 0x65, 0x73, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x7d, 0x0a, 0x14, 0x71, 0x75, 0x65, 0x72,
	0x79, 0x47, 0x75, 0x65, 0x73, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x67, 0x75, 0x65, 0x73, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x67, 0x75, 0x65, 0x73, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x2f,
	0x0a, 0x09, 0x67, 0x75, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x73, 0x65, 0x72, 0x73, 0x70, 0x62, 0x2e, 0x67,
	0x75, 0x65, 0x73, 0x73, 0x52, 0x09, 0x67, 0x75, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x22, 0x2a, 0x0a, 0x12, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x50, 0x72, 0x69, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72,
	0x69, 0x6d, 0x65, 0x22, 0x5b, 0x0a, 0x09, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x64, 0x65, 0x74, 0x73,
	0x12, 0x1c, 0x0a, 0x09, 0x67, 0x75, 0x65, 0x73, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x67, 0x75, 0x65, 0x73, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69,
	0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x4e, 0x75, 0x6d, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x4e, 0x75, 0x6d,
	0x22, 0x52, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x12,
	0x33, 0x0a, 0x09, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x73, 0x65, 0x72, 0x73, 0x70, 0x62, 0x2e,
	0x70, 0x72, 0x69, 0x6d, 0x65, 0x64, 0x65, 0x74, 0x73, 0x52, 0x09, 0x70, 0x72, 0x69, 0x6d, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x50, 0x0a, 0x13, 0x71, 0x75, 0x65, 0x72, 0x79, 0x50, 0x72, 0x69,
	0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x29, 0x0a, 0x06, 0x70,
	0x72, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x75,
	0x65, 0x73, 0x73, 0x65, 0x72, 0x73, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x52, 0x06,
	0x70, 0x72, 0x69, 0x6d, 0x65, 0x73, 0x32, 0xd8, 0x02, 0x0a, 0x08, 0x67, 0x75, 0x65, 0x73, 0x73,
	0x65, 0x72, 0x73, 0x12, 0x4d, 0x0a, 0x0a, 0x61, 0x64, 0x64, 0x47, 0x75, 0x65, 0x73, 0x73, 0x65,
	0x72, 0x12, 0x1d, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x73, 0x65, 0x72, 0x73, 0x70, 0x62, 0x2e, 0x61,
	0x64, 0x64, 0x47, 0x75, 0x65, 0x73, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1e, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x73, 0x65, 0x72, 0x73, 0x70, 0x62, 0x2e, 0x61, 0x64,
	0x64, 0x47, 0x75, 0x65, 0x73, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x56, 0x0a, 0x0d, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x47, 0x75, 0x65, 0x73,
	0x73, 0x65, 0x72, 0x12, 0x20, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x73, 0x65, 0x72, 0x73, 0x70, 0x62,
	0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x47, 0x75, 0x65, 0x73, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x73, 0x65, 0x72, 0x73,
	0x70, 0x62, 0x2e, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x47, 0x75, 0x65, 0x73, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x0c, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x47, 0x75, 0x65, 0x73, 0x73, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x67, 0x75, 0x65,
	0x73, 0x73, 0x65, 0x72, 0x73, 0x70, 0x62, 0x2e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x47, 0x75, 0x65,
	0x73, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x67, 0x75,
	0x65, 0x73, 0x73, 0x65, 0x72, 0x73, 0x70, 0x62, 0x2e, 0x71, 0x75, 0x65, 0x72, 0x79, 0x47, 0x75,
	0x65, 0x73, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x50, 0x0a, 0x0b, 0x71, 0x75, 0x65, 0x72, 0x79, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x1e,
	0x2e, 0x67, 0x75, 0x65, 0x73, 0x73, 0x65, 0x72, 0x73, 0x70, 0x62, 0x2e, 0x71, 0x75, 0x65, 0x72,
	0x79, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x67, 0x75, 0x65, 0x73, 0x73, 0x65, 0x72, 0x73, 0x70, 0x62, 0x2e, 0x71, 0x75, 0x65, 0x72,
	0x79, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x21, 0x5a, 0x1f, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x67, 0x75, 0x65, 0x73,
	0x73, 0x65, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_guessers_proto_rawDescOnce sync.Once
	file_guessers_proto_rawDescData = file_guessers_proto_rawDesc
)

func file_guessers_proto_rawDescGZIP() []byte {
	file_guessers_proto_rawDescOnce.Do(func() {
		file_guessers_proto_rawDescData = protoimpl.X.CompressGZIP(file_guessers_proto_rawDescData)
	})
	return file_guessers_proto_rawDescData
}

var file_guessers_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_guessers_proto_goTypes = []interface{}{
	(*AddGuesserRequest)(nil),     // 0: guesserspb.addGuesserRequest
	(*AddGuesserResponse)(nil),    // 1: guesserspb.addGuesserResponse
	(*RemoveGuesserRequest)(nil),  // 2: guesserspb.removeGuesserRequest
	(*RemoveGuesserResponse)(nil), // 3: guesserspb.removeGuesserResponse
	(*Guess)(nil),                 // 4: guesserspb.guess
	(*QueryGuesserRequest)(nil),   // 5: guesserspb.queryGuesserRequest
	(*QueryGuesserResponse)(nil),  // 6: guesserspb.queryGuesserResponse
	(*QueryPrimesRequest)(nil),    // 7: guesserspb.queryPrimesRequest
	(*Primedets)(nil),             // 8: guesserspb.primedets
	(*Prime)(nil),                 // 9: guesserspb.prime
	(*QueryPrimesResponse)(nil),   // 10: guesserspb.queryPrimesResponse
}
var file_guessers_proto_depIdxs = []int32{
	4,  // 0: guesserspb.queryGuesserResponse.guessList:type_name -> guesserspb.guess
	8,  // 1: guesserspb.prime.primeList:type_name -> guesserspb.primedets
	9,  // 2: guesserspb.queryPrimesResponse.primes:type_name -> guesserspb.prime
	0,  // 3: guesserspb.guessers.addGuesser:input_type -> guesserspb.addGuesserRequest
	2,  // 4: guesserspb.guessers.removeGuesser:input_type -> guesserspb.removeGuesserRequest
	5,  // 5: guesserspb.guessers.queryGuesser:input_type -> guesserspb.queryGuesserRequest
	7,  // 6: guesserspb.guessers.queryPrimes:input_type -> guesserspb.queryPrimesRequest
	1,  // 7: guesserspb.guessers.addGuesser:output_type -> guesserspb.addGuesserResponse
	3,  // 8: guesserspb.guessers.removeGuesser:output_type -> guesserspb.removeGuesserResponse
	6,  // 9: guesserspb.guessers.queryGuesser:output_type -> guesserspb.queryGuesserResponse
	10, // 10: guesserspb.guessers.queryPrimes:output_type -> guesserspb.queryPrimesResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_guessers_proto_init() }
func file_guessers_proto_init() {
	if File_guessers_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_guessers_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGuesserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guessers_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGuesserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guessers_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveGuesserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guessers_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveGuesserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guessers_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Guess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guessers_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryGuesserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guessers_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryGuesserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guessers_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryPrimesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guessers_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Primedets); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guessers_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Prime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_guessers_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryPrimesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_guessers_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_guessers_proto_goTypes,
		DependencyIndexes: file_guessers_proto_depIdxs,
		MessageInfos:      file_guessers_proto_msgTypes,
	}.Build()
	File_guessers_proto = out.File
	file_guessers_proto_rawDesc = nil
	file_guessers_proto_goTypes = nil
	file_guessers_proto_depIdxs = nil
}
