// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: numbers.proto

package numbers

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddNumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int64 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *AddNumRequest) Reset() {
	*x = AddNumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_numbers_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddNumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNumRequest) ProtoMessage() {}

func (x *AddNumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_numbers_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNumRequest.ProtoReflect.Descriptor instead.
func (*AddNumRequest) Descriptor() ([]byte, []int) {
	return file_numbers_proto_rawDescGZIP(), []int{0}
}

func (x *AddNumRequest) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type AddNumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok  bool  `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Num int64 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *AddNumResponse) Reset() {
	*x = AddNumResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_numbers_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddNumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNumResponse) ProtoMessage() {}

func (x *AddNumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_numbers_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNumResponse.ProtoReflect.Descriptor instead.
func (*AddNumResponse) Descriptor() ([]byte, []int) {
	return file_numbers_proto_rawDescGZIP(), []int{1}
}

func (x *AddNumResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AddNumResponse) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type GetNumsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetNumsRequest) Reset() {
	*x = GetNumsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_numbers_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNumsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNumsRequest) ProtoMessage() {}

func (x *GetNumsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_numbers_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNumsRequest.ProtoReflect.Descriptor instead.
func (*GetNumsRequest) Descriptor() ([]byte, []int) {
	return file_numbers_proto_rawDescGZIP(), []int{2}
}

type GetNumsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok      bool            `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	NumsMap map[int64]int64 `protobuf:"bytes,2,rep,name=numsMap,proto3" json:"numsMap,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *GetNumsResponse) Reset() {
	*x = GetNumsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_numbers_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetNumsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNumsResponse) ProtoMessage() {}

func (x *GetNumsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_numbers_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNumsResponse.ProtoReflect.Descriptor instead.
func (*GetNumsResponse) Descriptor() ([]byte, []int) {
	return file_numbers_proto_rawDescGZIP(), []int{3}
}

func (x *GetNumsResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GetNumsResponse) GetNumsMap() map[int64]int64 {
	if x != nil {
		return x.NumsMap
	}
	return nil
}

type RemoveNumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int64 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *RemoveNumRequest) Reset() {
	*x = RemoveNumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_numbers_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveNumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNumRequest) ProtoMessage() {}

func (x *RemoveNumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_numbers_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNumRequest.ProtoReflect.Descriptor instead.
func (*RemoveNumRequest) Descriptor() ([]byte, []int) {
	return file_numbers_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveNumRequest) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type RemoveNumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok  bool  `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Num int64 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *RemoveNumResponse) Reset() {
	*x = RemoveNumResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_numbers_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveNumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNumResponse) ProtoMessage() {}

func (x *RemoveNumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_numbers_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNumResponse.ProtoReflect.Descriptor instead.
func (*RemoveNumResponse) Descriptor() ([]byte, []int) {
	return file_numbers_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveNumResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RemoveNumResponse) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type QueryNumberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int64 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *QueryNumberRequest) Reset() {
	*x = QueryNumberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_numbers_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryNumberRequest) ProtoMessage() {}

func (x *QueryNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_numbers_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryNumberRequest.ProtoReflect.Descriptor instead.
func (*QueryNumberRequest) Descriptor() ([]byte, []int) {
	return file_numbers_proto_rawDescGZIP(), []int{6}
}

func (x *QueryNumberRequest) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type QueryNumberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok  bool  `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Num int64 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *QueryNumberResponse) Reset() {
	*x = QueryNumberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_numbers_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryNumberResponse) ProtoMessage() {}

func (x *QueryNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_numbers_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryNumberResponse.ProtoReflect.Descriptor instead.
func (*QueryNumberResponse) Descriptor() ([]byte, []int) {
	return file_numbers_proto_rawDescGZIP(), []int{7}
}

func (x *QueryNumberResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *QueryNumberResponse) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

var File_numbers_proto protoreflect.FileDescriptor

var file_numbers_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x70, 0x62, 0x22, 0x21, 0x0a, 0x0d, 0x61, 0x64,
	0x64, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6e,
	0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x32, 0x0a,
	0x0e, 0x61, 0x64, 0x64, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12,
	0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6e, 0x75,
	0x6d, 0x22, 0x10, 0x0a, 0x0e, 0x67, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0xa0, 0x01, 0x0a, 0x0f, 0x67, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x41, 0x0a, 0x07, 0x6e, 0x75, 0x6d, 0x73, 0x4d,
	0x61, 0x70, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x70, 0x62, 0x2e, 0x67, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4e, 0x75, 0x6d, 0x73, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x07, 0x6e, 0x75, 0x6d, 0x73, 0x4d, 0x61, 0x70, 0x1a, 0x3a, 0x0a, 0x0c, 0x4e, 0x75,
	0x6d, 0x73, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x24, 0x0a, 0x10, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x35, 0x0a, 0x11,
	0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f,
	0x6b, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x6e, 0x75, 0x6d, 0x22, 0x26, 0x0a, 0x12, 0x71, 0x75, 0x65, 0x72, 0x79, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x37, 0x0a, 0x13, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02,
	0x6f, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x6e, 0x75, 0x6d, 0x32, 0xa9, 0x02, 0x0a, 0x07, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73,
	0x12, 0x3f, 0x0a, 0x06, 0x61, 0x64, 0x64, 0x4e, 0x75, 0x6d, 0x12, 0x18, 0x2e, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x70, 0x62, 0x2e, 0x61, 0x64, 0x64, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x70, 0x62,
	0x2e, 0x61, 0x64, 0x64, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x42, 0x0a, 0x07, 0x67, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x73, 0x12, 0x19, 0x2e, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x70, 0x62, 0x2e, 0x67, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x70, 0x62, 0x2e, 0x67, 0x65, 0x74, 0x4e, 0x75, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a, 0x09, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4e,
	0x75, 0x6d, 0x12, 0x1b, 0x2e, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x70, 0x62, 0x2e, 0x72,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x70, 0x62, 0x2e, 0x72, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x4f, 0x0a, 0x0c, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x1d, 0x2e, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x70, 0x62, 0x2e, 0x71, 0x75, 0x65, 0x72,
	0x79, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e,
	0x2e, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x70, 0x62, 0x2e, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x20, 0x5a, 0x1e, 0x6f, 0x6e, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x69, 0x6e, 0x67, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_numbers_proto_rawDescOnce sync.Once
	file_numbers_proto_rawDescData = file_numbers_proto_rawDesc
)

func file_numbers_proto_rawDescGZIP() []byte {
	file_numbers_proto_rawDescOnce.Do(func() {
		file_numbers_proto_rawDescData = protoimpl.X.CompressGZIP(file_numbers_proto_rawDescData)
	})
	return file_numbers_proto_rawDescData
}

var file_numbers_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_numbers_proto_goTypes = []interface{}{
	(*AddNumRequest)(nil),       // 0: numberspb.addNumRequest
	(*AddNumResponse)(nil),      // 1: numberspb.addNumResponse
	(*GetNumsRequest)(nil),      // 2: numberspb.getNumsRequest
	(*GetNumsResponse)(nil),     // 3: numberspb.getNumsResponse
	(*RemoveNumRequest)(nil),    // 4: numberspb.removeNumRequest
	(*RemoveNumResponse)(nil),   // 5: numberspb.removeNumResponse
	(*QueryNumberRequest)(nil),  // 6: numberspb.queryNumberRequest
	(*QueryNumberResponse)(nil), // 7: numberspb.queryNumberResponse
	nil,                         // 8: numberspb.getNumsResponse.NumsMapEntry
}
var file_numbers_proto_depIdxs = []int32{
	8, // 0: numberspb.getNumsResponse.numsMap:type_name -> numberspb.getNumsResponse.NumsMapEntry
	0, // 1: numberspb.numbers.addNum:input_type -> numberspb.addNumRequest
	2, // 2: numberspb.numbers.getNums:input_type -> numberspb.getNumsRequest
	4, // 3: numberspb.numbers.removeNum:input_type -> numberspb.removeNumRequest
	6, // 4: numberspb.numbers.query_number:input_type -> numberspb.queryNumberRequest
	1, // 5: numberspb.numbers.addNum:output_type -> numberspb.addNumResponse
	3, // 6: numberspb.numbers.getNums:output_type -> numberspb.getNumsResponse
	5, // 7: numberspb.numbers.removeNum:output_type -> numberspb.removeNumResponse
	7, // 8: numberspb.numbers.query_number:output_type -> numberspb.queryNumberResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_numbers_proto_init() }
func file_numbers_proto_init() {
	if File_numbers_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_numbers_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddNumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_numbers_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddNumResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_numbers_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNumsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_numbers_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetNumsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_numbers_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveNumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_numbers_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveNumResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_numbers_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryNumberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_numbers_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryNumberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_numbers_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_numbers_proto_goTypes,
		DependencyIndexes: file_numbers_proto_depIdxs,
		MessageInfos:      file_numbers_proto_msgTypes,
	}.Build()
	File_numbers_proto = out.File
	file_numbers_proto_rawDesc = nil
	file_numbers_proto_goTypes = nil
	file_numbers_proto_depIdxs = nil
}
